package com.rachel.taskManager.dto;

import lombok.Data;

@Data
public class UpdateRoleRequest {
    // A DTO to represent a request to update a user's role in the system.
    
    private String newRole;

    // Getters and Setters are generated by Lombok's @Data annotation
    // public String getNewRole() {
    //     return newRole;
    // }

    // public void setNewRole(String newRole) {
    //     this.newRole = newRole;
    // }
}
